@startuml classes

' hide circle
skinparam linetype ortho

class Aluno {
    - nome : String
    - endereco : String
    - telefone : String
    - dataNascimento : String 
}

class Curso {
    - nome : String
    - descricao : String
    - cargaHoraria : int
    - dataInicio : String
    - dataFim : String
}

class Turma {
    - nome : String
    - matriculas : List<Matricula>
}

class Matricula {
    - codigo: String
    - aluno : Aluno
    - curso : Curso
    - dataMatricula : String
}
@enduml