version: "3"
services:
    db:
        image: mariadb:10.5
        container_name: "mariadb-oop"
        restart: always
        volumes:
            - ./banco.sql:/docker-entrypoint-initdb.d/banco.sql
        environment:
            - MARIADB_USER=root
            - MARIADB_ROOT_PASSWORD=123
        ports:
            - 3307:3306

    adminer:
        image: adminer:4.8.1
        container_name: "adminer-oop"
        restart: always
        ports:
            - 8080:8080
